### ISSUE TITLE
Crear lista ligada

### ISSUE THREAD

**Issue by yoinergomez** [yoinergomez/Pruebas_PS0#6]
Funciones a implementar de la lista:
- Añadir nodo.
- Eliminar nodo.
- Próximo nodo.
- Anterior nodo.

Nota: La lista va ser de tipo doblemente ligada con nodo cabeza. En el dato cabeza se almacena la cantidad de nodos.

**Comment by FrankAlexisDev** [comment]
Eliminar nodo, se pasa como parámetro el nodo a eliminar o un dato. En el caso del dato se tiene que eliminar todos los que coincidan o solo el primero?

**Comment by yoinergomez** [comment]
Como lo crea más pertinente. Es libre de tomar cualquier decisión. :smile:
